### PR TITLE
Fix docstring, add a couple features to ESP driver

### PR DESCRIPTION
**Pull request by bbrelje**
## Purpose
This adds a couple of important guardrails to ESP, including an automatic error raised if the point set isn't close enough to the ESP surface, and a way to suppress edge matching (sometimes edges parameterize weirdly for some reason when the surfaces are fine)

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [X] I have run unit and regression tests which pass locally with my changes
- [X] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by anilyil — DISMISSED** [review]
these look good to me. do you want me to dig deeper into the code @bbrelje?

**Review by joanibal — APPROVED** [review]

**Comment by nwu63** [comment]
Do we also want to make a new release? OpenVSP and ESP have been added since the last release.

**Comment by bbrelje** [comment]
@nwu63 yeah a new release is a good idea, thanks

**Review by nwu63 — APPROVED** [review]

**Comment by nwu63** [comment]
Merging since we had two approvals before I bumped the version.

**Pull request merged**
