### PR TITLE
added custom option to write_wing_FFD_file

### PR DESCRIPTION
**Pull request by yqliaohk**
Add an option to provide user's defined distributions in write_wing_FFD_file

### CODE REVIEW

**Comment by anilyil** [comment]
Is this PR still active? #23 seems to have an option to pass in a custom spacing to the FFD utility function. Check: https://github.com/mdolab/pygeo/pull/23/files?file-filters%5B%5D=.py#diff-b16be9897696e273b2f0e267523343e4R445

**Comment by nbons** [comment]
Yes, it turns out that Yingqian and I both implemented similar
functionality independently, but since my PR was still sitting in the
queue, she wasn't aware of it.

**Comment by yqliaohk** [comment]
Ok, yes, I didn't know that. I think @nbons implementation is more consistent with the overall function. I can just close this if that one get merged.

**Comment by anilyil** [comment]
Sure, I will merge @nbons's PR soon, so you can use his version after we merge. I can close this PR after I merge his.

**Pull request closed without merging**
