### PR TITLE
pyGeo.py test

### PR DESCRIPTION
**Pull request by hajdik**
## Purpose
A test has been added to start coverage of `pyGeo.py`. This test is based on the `generate_wing.py` script from the MACH-Aero tutorial. That script is run and then the resulting surface data is summed and compared to a reference file. This is summed rather than directly compared to avoid saving and comparing a long file.  

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [X] Maintenance update
- [ ] Other (please describe)

## Testing
Tests should run with latest input files folder

## Checklist
- [X] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [X] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by marcomangano** [comment]
Nice, the new `BaseRegTest` seems to have fixed the mismatches on different images... but I am not very happy about having a 70k lines ref file. We should find a better way to compare the output file, this is pretty brute force

**Comment by nwu63** [comment]
> Nice, the new `BaseRegTest` seems to have fixed the mismatches on different images... but I am not very happy about having a 70k lines ref file. We should find a better way to compare the output file, this is pretty brute force

Good point, we probably want to do some reduction. `par_add_sum` might be a good candidate, i.e. just sum everything and compare that.

**Review by nwu63 — APPROVED** [review]
LGTM

**Review by marcomangano — APPROVED** [review]
Nice

**Pull request merged**
