### PR TITLE
Pass the DVname of VSP design variable to vspDV class 

### PR DESCRIPTION
**Pull request by ArshSaja**
## Purpose

The DVname in vspDV class was set to None. Thus, when `dv.name` is called, it returns `None`. This PR fixes this issue.
## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by joanibal** [comment]
Can you provide more context here. Was the code broken before? What is wrong with using `dv.name`?

**Comment by hajdik** [comment]
> For openvsp, since we don't pass the DV name in `vspDV` class, we set the name of DV as `None`. 
Is there a reason we couldn't add names to VSP DVs to keep a more consistent API across the different DVGeo types and DV types? The name is already present in as the key in `self.DVs`, right?

**Comment by ArshSaja** [comment]
I changed it to the default case. Now the DV name is passed to the `vspDV` class.

**Review by hajdik — APPROVED** [review]

**Comment by eirikurj** [comment]
@ArshSaja can you update the PR name and purpose to be consistent with the content

**Comment by ArshSaja** [comment]
I updated the PR details. @eirikurj

**Review by marcomangano — APPROVED** [review]

**Pull request merged**
