### PR TITLE
Volume projection bounds

### PR DESCRIPTION
**Pull request by anilyil**
## Purpose

This PR adds the capability to set parametric bounds in the embedding volume of each FFD box. This is useful to control the behavior of overlapping FFDs, where the user wants to avoid embedding any point in one portion of one or both of the FFDs. 

This PR needs changes in https://github.com/mdolab/pyspline/pull/63 to work. 

## Expected time until merged

After https://github.com/mdolab/pyspline/pull/63 is merged.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by lamkina — APPROVED** [review]
This PR looks good to go.  We had to trigger the CI checks and tests manually on Azure so they are not showing up here, but they all passed.

**Review by hajdik — APPROVED** [review]

**Comment by hajdik** [comment]
I can't merge it with the failures, @anilyil can you do it?

**Comment by sseraj** [comment]
Did anyone actually run this on Azure? The tests are failing

**Comment by lamkina** [comment]
> Did anyone actually run this on Azure? The tests are failing

We tried to manually run an Azure and accidentally ran the wrong PR and didn't realize it.

**Comment by sseraj** [comment]
Ah okay, I see that manual run. For future reference, the checks in PRs should be updated even if you manually run the pipeline (as long as it's the correct commit).

**Pull request merged**
