### PR TITLE
File splitting

### LINKED ISSUE #81: Reorganize the repo
# Description
There are several unnecessarily large files in this repo:
- `DVConstraints.py` has 6468 lines
- `DVGeometry.py` has 4541 lines
- `geo_utils.py` has 4509 lines

We should move some code into new files. For example, we should have separate files for separate constraint and DV classes instead of having them all in the same file. These files can be stored in separate directories.

### PR DESCRIPTION
**Pull request by kanekosh**
## Purpose
Closes #81.

Splitted large files: `geo_utils.py, DVConstraints.py, DVGeometry.py`.
```
pygeo/pygeo
|
|-- geo_utils
|   |-- __init__.py
|   |-- all functions previously in geo_utils.py
|
|-- constraints
|   |-- all classes previously in DVConstraints.py
|
|-- geometry
|   |-- all classes previously in DVGeometry.py 
|
|-- __init__.py
|-- other python files
```

- Replaced Error classes in `DVConstraints.py` and `DVGeometry.py` with the baseclasses Error. Also removed the Warning class in `DVConstraints.py` because it was not used anywhere.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by kanekosh** [comment]
It's ready for review now

**Comment by nwu63** [comment]
In theory this should not break any backwards compatibility, so I am going to build a docker container with this branch of pygeo and make sure everything runs.

**Review by nwu63 — CHANGES_REQUESTED** [review]
It seems that `DVGeo.py` was preserved but `DVCon.py` was not. Not a dealbreaker but it would have been nice to at least preserve file history for those two since they are the largest files.

A few other things I'd like to see in this PR:
- `pygeo/geo_utils/knowvector.py` should be `knotvector.py` I presume
- `DVGeometryAxi`, `DVGeometryESP` and `DVGeometryVSP` should be moved to under the `geometry` directory

**Comment by nwu63** [comment]
Okay, after discussing with @hajdik, we decided to fix the missing history for DVCon. We will open a new branch from the last of @kanekosh's commits, and use this branch as a reference to re-do the commits, but preserving the history when possible. It should not take too much time but the plan is to eventually open a new one instead of this, perhaps some time next week.

**Comment by nwu63** [comment]
Superseded by #94.

**Pull request closed without merging**
