### PR TITLE
`readPlot3DSurfFile` never closes file after opening it

### PR DESCRIPTION
**Pull request by eytanadler**
## Purpose

When initializing a `DVGeometry` object, one way to specify the FFD file is to provide its filename. The function responsible for reading this file opens it, but never closes it. This can cause file system problems. I changed it to put the code that reads from the file in a `with` block so that it is closed upon exiting (either a raised error or function return).

## Expected time until merged

1 day

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by hajdik — DISMISSED** [review]
Nice

**Review by marcomangano — COMMENTED** [review]
Looks like the previous function `getCoordinatesFromFile` uses `f.open()` and `f.close()`, could you update that and other functions to use `with`?

**Comment by eytanadler** [comment]
> Looks like the previous function `getCoordinatesFromFile` uses `f.open()` and `f.close()`, could you update that and other functions to use `with`?

Sure thing. I'm pretty sure `np.loadtxt()` could replace this entire function, but I can't find any examples of this method being used so I have no idea what file type it's meant for.

**Review by hajdik — APPROVED** [review]
very nice

**Review by marcomangano — APPROVED** [review]

**Pull request merged**
